### ISSUE TITLE
Application Pybind Warning

### ISSUE THREAD

**Issue by nsoblath** [project8/scarab#52]
Currently compiling application_pybind.hh gives a warning: `control may reach end of non-void lambda`.

This is because the `CLI_PARSE` macro returns an `int` in the event that the app throws a `CLI::ParseError`.

We should just make the `execute()` function of the binding return an `int` in successful executions.

**Comment by laroque** [comment]
Thanks, I'd seen this warning and wasn't sure why the lambda wasn't void. I'm just going to include the fix in the next feature PR, since those are coming relatively quickly.
